### ISSUE TITLE
Document Title not updating on all tanstack.com pages

### ISSUE THREAD

**Issue by dimitropoulos** [TanStack/tanstack.com#48] opened 2022-11-03 14:32 UTC
Hi!

I happened to notice that [document.title](https://developer.mozilla.org/en-US/docs/Web/API/Document/title) isn't getting updated when you navigate within pages in any of the pre-defined routes.

Reproduction steps:
1. navigate to https://tanstack.com/query/v4/docs/guides/scroll-restoration
	- observe that the document title (i.e. in the browser tab) reads `Scroll Restoration | Tanstack Query Docs`
1. click on "Filters" at the bottom of the page (or in the sidebar, it's the next item in the list)
    - observe the url changed to https://tanstack.com/query/v4/docs/guides/filters
    - observe that the document title has not changed
1. refresh the page
    - observe that the document title now correctly reads `Filters | Tanstack Query Docs`

This happens on other sites on tanstack.com as well, e.g. https://tanstack.com/table and others.

I looked for a quick solution so I could contribute it, but after like 90 seconds of looking I see that it's controlled by the utils/seo function which is integrated in to remix, and I don't have enough experience with remix to fix it quickly.

**Comment by crutchcorn** [comment] 2024-01-09 02:04
Closing, as I cannot reproduce this issue anymore. Please reopen should you continue to experience this problem :)

**Closed by crutchcorn** 2024-01-09 02:04 UTC
Labels: bug
