### ISSUE TITLE
The TanStack Store React quick start page has too many redirects

### ISSUE THREAD

**Issue by richardtknight** [TanStack/tanstack.com#129] opened 2023-12-23 16:25 UTC
### Describe the bug

The link to "[quick start](https://tanstack.com/store/latest/docs/framework/react/quick-start)" doesn't load anything, and if you open it in a new tab, eventually it resolves into an ERR_TOO_MANY_REDIRECTS error being thrown as per the screenshot attached.

### Your Example Website or App

https://tanstack.com/store/latest/docs/framework/react/quick-start

### Steps to Reproduce the Bug or Issue

1. Go to the TanStack store documentation [overview page](https://tanstack.com/store/latest/docs/overview)
2. Click "Quick Start" in the left hand menu
3. Wait...

### Expected behavior

As a user I expected the quick start page to load.

### Screenshots or Videos

<img width="1510" alt="Screenshot 2023-12-23 at 16 20 25" src="https://github.com/TanStack/store/assets/16280330/85c02f71-4e56-4cf0-9d0e-1c20f4415e1e">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by fulopkovacs** [comment] 2024-01-12 22:26
https://github.com/TanStack/tanstack.com/pull/133 will fix this ([See this comment](https://github.com/TanStack/tanstack.com/pull/133/files/09bd3f53bd4c8ceb894d9b0a09137f9889a5488a#r1439069701)).


Basically, the example routes are not set up correctly. When the user loads `/store/latest/framework/react/quick-start` it matches the `store.$version.docs.framework.$framework.$examples._index.tsx` route, where `$examples` is a dynamic segment. 

> [!NOTE] 
> These are the value of the [route params](https://remix.run/docs/en/main/guides/data-loading#route-params): `{version: "latest", framework: "react", examples: "quick-start`}`

The problem is that this is the loader of `store.$version.docs.framework.$framework.$examples._index.tsx`:
```tsx
export const loader = (context: LoaderFunctionArgs) => {
  throw redirect(context.request.url.replace('/examples/', `/examples/simple`))
}
```
Since `context.request.url` does not contain `'/examples/'`, it'll just redirect the route to itself. This is where the infinite redirects come from.


The solution is simply to drop the `$` from `$examples` in examples' routes:
- `app/routes/store.$version.docs.framework.$framework.$examples._index.tsx` -> `app/routes/store.$version.docs.framework.$framework.examples._index.tsx`
- app/routes/store.$version.docs.framework.$framework.$examples.$.tsx -> app/routes/store.$version.docs.framework.$framework.examples.$.tsx

I think it's just a typo, because the form routes already look like the fixed version.

**Comment by crutchcorn** [comment] 2024-01-15 22:50
Closed, as @fulopkovacs's work is merged! Thank you!!

**Closed by crutchcorn** 2024-01-15 22:50 UTC
Labels: bug
